name: deploy to gh-pages branch
on:
  push:
    tags:
      - "*"
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: |
          git config --global user.name 'Github actions'
          git config --global user.email 'no-reply@github.com'
          npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
